import test from 'node:test';
import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {QueryClient} from '@tanstack/react-query';
import {ProducaoEspelhoView,formatarValorEspelho} from '../components/controle/ProducaoEspelhoPainel';
import {decodificarConsultaEspelho,decodificarConsultaQuadro,autoridadeEspelhoValida,chaveConsultaEspelho,consultarEspelho,consultarQuadroEspelho,criarCicloEspelho,consultaEspelhoRemovivel,dadosEspelhoVisiveis,codificarFiltroEspelho,filtrarEspelho,paginarEspelho,selecionarEspelhoPagina,chaveSelecaoEspelho,type AutoridadeEspelho,type DepsConsultaEspelho} from './producao-espelho-consulta';
const id=(n:number)=>`00000000-0000-4000-8abc-${n.toString(16).padStart(12,'0')}`;
const stamp='2026-10-01T20:38:12.028294+00',instant='2026-10-01T20:38:12.028Z';
const rawCard=(n=1,extra:Record<string,unknown>={})=>({id:id(n),pedido_id:'MANUAL-X',cliente_nome:'<img inert-name>',vendedor_nome:'todos',status:'UNKNOWN',doc_original_path:'javascript:inert-path',created_at:stamp,updated_at:stamp,excluido:false,doc_tratado_path:null,prazo_dias:null,prazo_tipo:null,prazo_data:null,observacoes:null,numero_orcamento:null,motor_marca:null,motor_tensao:null,resumo_equipamentos:null,titulo_equipamento:null,codigo_rastreio:null,cidade_destino:null,observacao_vendedor:null,parado_status:null,parado_motivo:null,orcamento_revisado_info:null,motor_tensao_vendedor:null,excluido_em:null,parado_em:null,orcamento_revisado_em:null,orcamento_revisado_visto_em:null,excluido_por:null,checklist_compras:null,...extra});
const history=(n=1)=>({id:id(n+100),card_id:id(1),old_status:null,new_status:'UNKNOWN',changed_at:stamp,changed_by:null,cliente_nome:null,numero_orcamento:null});
const logistics=()=>({card_id:id(1),peso_kg:'12345678901234567890.123456789',qtd_volumes:null,medidas:null,observacoes:null,updated_at:stamp,updated_by:null});
const sector=(n=1)=>({id:id(n+200),card_id:id(1),setor:'constructor',responsavel_id:null,previsao_termino:'Infinity',andamento:-1,status:null,motivo_bloqueio:null,iniciado_em:null,concluido_em:null,created_at:null,updated_at:null});
const check=(n=1)=>({id:id(n+300),setor_producao_id:id(201),titulo:'physical',descricao:null,ordem:null,concluido:null,concluido_por:null,concluido_em:null,created_at:null});
const card=(n=1,extra:Record<string,unknown>={})=>{const raw=rawCard(n,extra);return {id:raw.id,pedidoId:null,numeroOrcamento:raw.numero_orcamento,cliente:raw.cliente_nome,vendedor:raw.vendedor_nome,etapa:raw.status,atualizadoEm:raw.updated_at,dadosOriginais:{...raw,vinculo:'nao_verificado',historico:[],logistica:null,setores:[]}};};
const dto=(cards:ReturnType<typeof card>[]=[card()])=>({origem:'app2',fonte:'controle-producao-live',consultadoEm:instant,atualizadoEm:null,sincronizadoEm:null,parcial:false,aviso:'Independent reads',consistency:'crossread_unproved',complete:{cards:true,historico:true,logistica:true,setores:true,checklists:true},totals:{cards:cards.length,historico:0,logistica:0,setores:0,checklists:0},dados:{cards,kpis:{total:cards.length,excluidos:0,ativos:cards.length,entregues:0,cancelados:0,pedidosUnicos:0},porEtapa:cards.length?{UNKNOWN:cards.length}:{},porSetor:{}}});
const authority=(generation=1):AutoridadeEspelho=>({userId:id(999),profileId:id(999),role:'vendor',vendorId:id(998),approvedAt:instant,menu:true,loading:false,profileError:false,generation});
const unavailable=/Produção indisponível/;
const filters={busca:'',status:'',exclusao:'todos' as const,vendedor:''};

const projeto=()=>({id:id(700),card_id:id(1),responsavel_projeto_id:id(701),responsavel_nome:'Betuel <texto literal>',status_projeto:'em_andamento',andamento:40,previsao_termino:null,prazo_prometido:'2026-10-16',prazo_interno:null});
function lightDto(){const full=dto(),{historico,logistica,setores,...raw}=full.dados.cards[0].dadosOriginais;return {...full,visao:'quadro-v1',parcial:true,complete:{cards:true,historico:false,logistica:false,setores:false,checklists:false},totals:{cards:1,historico:null,logistica:null,setores:null,checklists:null},dados:{...full.dados,cards:[{...full.dados.cards[0],dadosOriginais:{...raw,projeto:projeto()}}],porSetor:null}};}

test('light decoder preserves known project data while rejecting fabricated unread totals and mismatched contracts',()=>{
  const out=decodificarConsultaQuadro(lightDto());assert.equal(out.dados.cards[0].dadosOriginais.projeto?.responsavel_nome,'Betuel <texto literal>');assert.equal(out.totals.historico,null);assert.equal(out.complete.historico,false);
  assert.equal(Object.prototype.hasOwnProperty.call(out.dados.cards[0].dadosOriginais,'historico'),false);
  for(const mutate of [(v:ReturnType<typeof lightDto>)=>{Object.assign(v.totals,{historico:0});},(v:ReturnType<typeof lightDto>)=>{Object.assign(v.complete,{historico:true});},(v:ReturnType<typeof lightDto>)=>{Object.assign(v,{visao:'unknown'});},(v:ReturnType<typeof lightDto>)=>{Object.assign(v.dados.cards[0].dadosOriginais,{historico:[]});},(v:ReturnType<typeof lightDto>)=>{Object.assign(v.dados.cards[0].dadosOriginais.projeto,{card_id:id(99)});},(v:ReturnType<typeof lightDto>)=>{Object.assign(v.dados,{porSetor:{}});}]){const data=lightDto();mutate(data);assert.throws(()=>decodificarConsultaQuadro(data),unavailable);}
  assert.throws(()=>decodificarConsultaEspelho(lightDto()),unavailable);assert.throws(()=>decodificarConsultaQuadro(dto()),unavailable);
});

test('light presenter identifies details not loaded without displaying fake empty collection totals',()=>{
  const html=renderToStaticMarkup(React.createElement(ProducaoEspelhoView,{data:decodificarConsultaQuadro(lightDto()),autorizado:true,identityKey:'light',loading:false,fetching:false,error:false,atualizar(){}}));
  assert.match(html,/Quadro carregado/);assert.match(html,/ainda não carregados/);assert.ok(!/Histórico: 0|Logística: 0|Setores: 0|Checklists: 0/.test(html));
});

test('light HTTP caller requests the opt-in contract and rejects late session or generation changes',async()=>{
  for(const changed of [false,true]){const c=caller(),deps:DepsConsultaEspelho={...c.deps,fetch:async(url,init)=>{assert.equal(url,'/api/controle-producao?origem=app2&visao=quadro-v1');assert.equal(init.cache,'no-store');return {ok:true,status:200,json:async()=>{if(changed)c.context.current.generation++;return lightDto();}};}};
    if(changed)await assert.rejects(consultarQuadroEspelho(deps),/Sessão alterada/);else assert.equal((await consultarQuadroEspelho(deps)).totals.setores,null);
  }
});

test('real cache separates full versus board and old mode cleanup never deletes another mounted reader',()=>{
  const qc=new QueryClient(),cycle=criarCicloEspelho(),a=authority(cycle.geracao),fullKey=chaveConsultaEspelho(a),boardKey=chaveConsultaEspelho(a,'quadro-v1'),other=criarCicloEspelho(),otherKey=chaveConsultaEspelho(authority(other.geracao),'quadro-v1');
  qc.setQueryData(fullKey,'full');qc.setQueryData(boardKey,'board');qc.setQueryData(otherKey,'other');assert.notDeepEqual(fullKey,boardKey);
  qc.removeQueries({predicate:q=>consultaEspelhoRemovivel(cycle,q.queryKey,a,undefined,'quadro-v1')});assert.equal(qc.getQueryData(fullKey),undefined);assert.equal(qc.getQueryData(boardKey),'board');assert.equal(qc.getQueryData(otherKey),'other');
  cycle.encerrar();qc.removeQueries({predicate:q=>consultaEspelhoRemovivel(cycle,q.queryKey,{...a,loading:true},undefined,'quadro-v1')});assert.equal(qc.getQueryData(boardKey),undefined);assert.equal(qc.getQueryData(otherKey),'other');qc.clear();
});
test('project lookup fields preserve responsible name and raw dates while stripping unrelated personal data',()=>{
  const input=dto(); Object.assign(input.dados.cards[0].dadosOriginais,{projeto:{...projeto(),email:'PRIVATE',role:'admin'}});
  const out=decodificarConsultaEspelho(input).dados.cards[0].dadosOriginais;
  assert.deepEqual(out.projeto,projeto());
  assert.equal(decodificarConsultaEspelho(dto()).dados.cards[0].dadosOriginais.projeto,undefined);
  Object.assign(input.dados.cards[0].dadosOriginais,{projeto:null});
  assert.equal(decodificarConsultaEspelho(input).dados.cards[0].dadosOriginais.projeto,null);
});
test('project identity, owner and responsible pair are strict without rejecting unknown physical project states',()=>{
  const valid={...projeto(),responsavel_projeto_id:null,responsavel_nome:null,status_projeto:'ESTADO_FUTURO'};
  const input=dto(); Object.assign(input.dados.cards[0].dadosOriginais,{projeto:valid});
  assert.deepEqual(decodificarConsultaEspelho(input).dados.cards[0].dadosOriginais.projeto,valid);
  for(const bad of [undefined,[],Object.create(projeto()),{...projeto(),id:'invalid'},{...projeto(),card_id:id(2)},{...projeto(),responsavel_projeto_id:null},{...projeto(),responsavel_nome:null},{...projeto(),responsavel_nome:3},{...projeto(),responsavel_nome:''},{...projeto(),responsavel_nome:'  '},{...projeto(),andamento:1.2},{...projeto(),prazo_interno:1}]){
    Object.assign(input.dados.cards[0].dadosOriginais,{projeto:bad});
    assert.throws(()=>decodificarConsultaEspelho(input),unavailable);
  }
});
test('project identity cannot be reused across two authorized cards',()=>{
  const input=dto([card(1),card(2)]);input.dados.porEtapa.UNKNOWN=2;
  Object.assign(input.dados.cards[0].dadosOriginais,{projeto:projeto()});
  Object.assign(input.dados.cards[1].dadosOriginais,{projeto:{...projeto(),card_id:id(2)}});
  assert.throws(()=>decodificarConsultaEspelho(input),unavailable);
});

test('closed physical decoder preserves precision, dates/nulls, unknown states and strips private extras',()=>{for(const json of ['9007199254740993','0.123456789012345678901','1e999','null','{"n": 9007199254740993}',null]){const input=dto([card(1,{checklist_compras:json,observacoes:'  raw  '})]);const out=decodificarConsultaEspelho({...input,PRIVATE:'hidden'});assert.equal(out.dados.cards[0].dadosOriginais.checklist_compras,json);assert.equal(out.dados.cards[0].atualizadoEm,stamp);assert.equal(out.dados.cards[0].dadosOriginais.observacoes,'  raw  ');assert.equal((out as unknown as Record<string,unknown>).PRIVATE,undefined);assert.equal(out.dados.cards[0].dadosOriginais.arquivo_fabrica_url,undefined);}assert.equal(decodificarConsultaEspelho(dto([])).totals.cards,0);});
test('all related physical collections, Map-safe stages/setors and raw numeric text remain exact',()=>{const input=dto();const raw=input.dados.cards[0].dadosOriginais as Record<string,unknown>;raw.status='__proto__';input.dados.cards[0].etapa='__proto__';raw.historico=[history()];raw.logistica=logistics();raw.setores=[{...sector(),checklists:[check()]}];input.totals={cards:1,historico:1,logistica:1,setores:1,checklists:1};input.dados.porEtapa=Object.fromEntries([['__proto__',1]]);input.dados.porSetor={constructor:1};const out=decodificarConsultaEspelho(input);assert.equal(out.dados.porEtapa.__proto__,1);assert.equal(out.dados.porSetor.constructor,1);assert.equal(out.dados.cards[0].dadosOriginais.logistica?.peso_kg,logistics().peso_kg);assert.equal(out.dados.cards[0].dadosOriginais.setores[0].checklists[0].concluido,null);assert.equal(out.dados.cards[0].dadosOriginais.setores[0].andamento,-1);});
test('full metadata/own totals/groupings/integer density/ref/UUID contracts fail integrally',()=>{const input=dto();const cases:unknown[]=[null,{...input,origem:'controle-interno'},{...input,fonte:'receiver'},{...input,parcial:true},{...input,consistency:'snapshot'},{...input,sincronizadoEm:instant},{...input,complete:{...input.complete,logistica:false}},{...input,totals:{...input.totals,cards:573}},{...input,totals:Object.create(input.totals)},{...input,dados:{...input.dados,kpis:{...input.dados.kpis,total:999}}},{...input,dados:{...input.dados,porEtapa:{UNKNOWN:999}}},{...input,dados:{...input.dados,cards:new Array(1)}},{...dto([card(),card()]),dados:{...input.dados,cards:[card(),{...card(),id:id(1).toUpperCase()}]}}];for(const bad of cases)assert.throws(()=>decodificarConsultaEspelho(bad),unavailable);for(const field of ['excluido','updated_at','checklist_compras']){const invalid=dto();delete (invalid.dados.cards[0].dadosOriginais as Record<string,unknown>)[field];assert.throws(()=>decodificarConsultaEspelho(invalid),unavailable);}for(const extra of [{prazo_dias:2147483648},{excluido:0},{checklist_compras:{n:1}},{checklist_compras:'Infinity'},{checklist_compras:'{"bad":}'},{excluido_por:'invalid'}])assert.throws(()=>decodificarConsultaEspelho(dto([card(1,extra)])),unavailable);});
test('nested IDs/ref aliases/duplicate logistics-like card/ref and confirmed marker are strict without guessing links',()=>{for(const relation of [{historico:[{...history(),card_id:id(2)}]}, {setores:[{...sector(),checklists:[{...check(),setor_producao_id:id(999)}]}]}, {logistica:{...logistics(),peso_kg:1}}, {logistica:{...logistics(),card_id:id(2)}}]){const input=dto();Object.assign(input.dados.cards[0].dadosOriginais,relation);assert.throws(()=>decodificarConsultaEspelho(input),unavailable);}const one=card(1,{pedido_id:id(901)}),two=card(2,{pedido_id:id(901).toUpperCase()});const input=dto([one,two]);for(const c of input.dados.cards){c.pedidoId=id(901) as never;c.dadosOriginais.vinculo='confirmado';}input.dados.kpis.pedidosUnicos=1;assert.equal(decodificarConsultaEspelho(input).dados.cards.length,2);one.pedidoId=null;assert.throws(()=>decodificarConsultaEspelho(input),unavailable);});
test('JSON depth/node/card/result/envelope UTF8 budgets reject wholly, huge legal number lexemes survive',()=>{let deep:unknown=null;for(let i=0;i<17;i++)deep=[deep];for(const json of [JSON.stringify(deep),JSON.stringify(Array.from({length:10000},()=>null)),JSON.stringify('é'.repeat(524288))])assert.throws(()=>decodificarConsultaEspelho(dto([card(1,{checklist_compras:json})])),unavailable);const many=dto(Array.from({length:9},(_,i)=>card(i+1,{checklist_compras:JSON.stringify('x'.repeat(950000))})));assert.throws(()=>decodificarConsultaEspelho(many),unavailable);assert.throws(()=>decodificarConsultaEspelho(dto([card(1,{observacoes:'é'.repeat(2000000)})])),unavailable);assert.equal(decodificarConsultaEspelho(dto([card(1,{checklist_compras:'1e999'})])).dados.cards[0].dadosOriginais.checklist_compras,'1e999');});
test('authorized exact capability, known six roles, identity readiness and synchronous data+error mask',()=>{const data=decodificarConsultaEspelho(dto());for(const role of ['admin','financeiro','vendor','mapa','marketing','visualizador']){const a={...authority(),role};assert.equal(autoridadeEspelhoValida(a),true);assert.equal(autoridadeEspelhoValida({...a,menu:false}),false);assert.equal(dadosEspelhoVisiveis(data,{...a,menu:false},false),undefined);}for(const change of [{role:'consultor'},{loading:true},{profileError:true},{profileId:id(3)},{approvedAt:null},{userId:null}])assert.equal(autoridadeEspelhoValida({...authority(),...change}),false);assert.equal(dadosEspelhoVisiveis(data,authority(),true),undefined);assert.equal(dadosEspelhoVisiveis(data,authority(),false),data);assert.equal(JSON.stringify(chaveConsultaEspelho(authority())).includes('token'),false);});
function caller(stage?:string,change?:(context:{current:AutoridadeEspelho;token:string;controller:AbortController})=>void,status=200){const context={current:authority(),token:'synthetic-A',controller:new AbortController()};let sessions=0;const captured:RequestInit[]=[];const tick=(name:string)=>{if(stage===name)change?.(context);};const deps={authority:context.current,signal:context.controller.signal,getCurrentAuthority:()=>context.current,getCurrentToken:()=>context.token,getSession:async()=>{sessions++;tick(sessions===1?'session-before':'session-after');return {user:{id:context.current.userId!},access_token:context.token};},fetch:async(url:string,init:RequestInit)=>{assert.equal(url,'/api/controle-producao?origem=app2');captured.push(init);tick('fetch');return {ok:status===200,status,json:async()=>{tick('json');return dto();}};}};return {context,deps,captured};}
test('caller fixed GET/no-store/current volatile token and authority around all awaits',async()=>{const c=caller();await consultarEspelho(c.deps);assert.equal(c.captured[0].method,'GET');assert.equal(c.captured[0].cache,'no-store');assert.equal(c.captured[0].signal,c.context.controller.signal);assert.deepEqual(c.captured[0].headers,{Authorization:'Bearer synthetic-A'});assert.equal(c.captured[0].body,undefined);});
for(const stage of ['session-before','fetch','json','session-after'])test(`live authority/token/user/abort races rejected after ${stage}`,async()=>{for(const change of [{role:'admin'},{vendorId:id(3)},{profileId:id(3)},{approvedAt:'changed'},{menu:false},{loading:true},{profileError:true},{generation:2}]){const c=caller(stage,x=>{x.current={...x.current,...change};});await assert.rejects(consultarEspelho(c.deps),/Sessão alterada/);}for(const mutate of [(x:ReturnType<typeof caller>['context'])=>{x.token='synthetic-B';},(x:ReturnType<typeof caller>['context'])=>{x.current={...x.current,userId:id(3)};},(x:ReturnType<typeof caller>['context'])=>x.controller.abort()]){const c=caller(stage,mutate);await assert.rejects(consultarEspelho(c.deps),/Sessão alterada/);}});
test('ABA changes final token/authority back but old generation and closed caller never revive',async()=>{const cycle=criarCicloEspelho(),c=caller('json',x=>{cycle.avancar();cycle.avancar();x.current={...x.current,generation:cycle.geracao};});c.context.current={...c.context.current,generation:cycle.geracao};c.deps.authority=c.context.current;await assert.rejects(consultarEspelho(c.deps),/Sessão alterada/);const old=caller('fetch',()=>cycle.encerrar());old.deps.getCurrentAuthority=()=>({...old.context.current,loading:!cycle.ativo});await assert.rejects(consultarEspelho(old.deps),/Sessão alterada/);});
test('status and SDK/JSON/session errors expose fixed messages; prior success with401/403 masked',async()=>{for(const [status,pattern] of [[401,/Sessão alterada/],[403,/Sem permissão/],[503,unavailable]] as const)await assert.rejects(consultarEspelho(caller(undefined,undefined,status).deps),pattern);for(const slot of ['getSession','fetch'] as const){const c=caller();const deps={...c.deps,[slot]:async()=>{throw Error('PRIVATE URL KEY');}};await assert.rejects(consultarEspelho(deps),unavailable);}const c=caller();c.deps.fetch=async()=>({ok:true,status:200,json:async()=>{throw Error('PRIVATE JSON');}});await assert.rejects(consultarEspelho(c.deps),unavailable);assert.equal(dadosEspelhoVisiveis(decodificarConsultaEspelho(dto()),authority(),true),undefined);});
test('real QueryClient old owner auth/obsolete/error/unmount predicates preserve new mount and other namespaces',async()=>{const qc=new QueryClient({defaultOptions:{queries:{retry:false,staleTime:30000}}});const old=criarCicloEspelho();old.avancar();old.avancar();const oldA=authority(old.geracao),oldKey=chaveConsultaEspelho(oldA);const fresh=criarCicloEspelho();fresh.avancar();const freshA=authority(fresh.geracao),freshKey=chaveConsultaEspelho(freshA);const data=decodificarConsultaEspelho(dto());qc.setQueryData(oldKey,data);let reads=0;await qc.fetchQuery({queryKey:freshKey,queryFn:async()=>{reads++;return data;}});assert.equal(reads,1);for(const ns of ['controle-mapa','controle-biblioteca','controle-producao'])qc.setQueryData([ns],data);for(const mode of ['auth','obsolete','error','unmount']){qc.setQueryData(oldKey,data);if(mode==='unmount')old.encerrar();const live=mode==='auth'?{...oldA,loading:true}:mode==='obsolete'?{...oldA,generation:fresh.geracao}:oldA;const predicate=(q:{queryKey:readonly unknown[]})=>consultaEspelhoRemovivel(old,q.queryKey,live,mode==='error'?JSON.stringify(oldKey):undefined);await qc.cancelQueries({predicate});qc.removeQueries({predicate});assert.equal(qc.getQueryData(oldKey),undefined);assert.equal(qc.getQueryData(freshKey),data);for(const ns of ['controle-mapa','controle-biblioteca','controle-producao'])assert.equal(qc.getQueryData([ns]),data);}assert.notEqual(fresh.geracao,old.geracao);qc.clear();});
test('AND physical filters preserve excluded/cancelled/status/null/empty/sentinel choices and all last pages',()=>{const decoded=decodificarConsultaEspelho(dto());const base=decoded.dados.cards[0];const cards=[{...base,id:id(1),vendedor:null},{...base,id:id(2),vendedor:''},{...base,id:id(3),vendedor:'todos',etapa:'CANCELADO',dadosOriginais:{...base.dadosOriginais,excluido:true}},{...base,id:id(4),vendedor:'null'}];for(const value of [null,'','todos','null'])assert.equal(filtrarEspelho(cards,{...filters,vendedor:codificarFiltroEspelho(value)}).length,1);assert.equal(filtrarEspelho(cards,{...filters,status:codificarFiltroEspelho('CANCELADO'),exclusao:'excluidos',vendedor:codificarFiltroEspelho('todos')}).length,1);assert.equal(filtrarEspelho(cards,{...filters,status:codificarFiltroEspelho('CANCELADO'),exclusao:'incluidos'}).length,0);const many=Array.from({length:51},(_,i)=>({...base,id:id(i+1)}));assert.equal(paginarEspelho(many,3).linhas[0].id,id(51));assert.equal(paginarEspelho(many,99).pagina,3);assert.equal(paginarEspelho(many,1).linhas.length,25);});
test('selection only current page/context and local revision prevents filter/page ABA resurrection',()=>{const cards=decodificarConsultaEspelho(dto()).dados.cards;const a=chaveSelecaoEspelho('identity',1,filters,1,cards),b=chaveSelecaoEspelho('identity',3,filters,1,cards);const selected={id:cards[0].id,context:a};assert.equal(selecionarEspelhoPagina(cards,selected,a),cards[0]);assert.equal(selecionarEspelhoPagina([],selected,a),undefined);assert.equal(selecionarEspelhoPagina(cards,selected,b),undefined);assert.equal(selecionarEspelhoPagina(cards,selected,'newidentity'),undefined);});
test('actual pure presenter synchronously masks retained metadata for denied/error/loading and escapes physical text',()=>{const data=decodificarConsultaEspelho(dto());const render=(authorized:boolean,error=false,loading=false)=>renderToStaticMarkup(React.createElement(ProducaoEspelhoView,{data,autorizado:authorized,error,loading,fetching:false,identityKey:'x',atualizar:()=>{}}));for(const html of [render(false),render(true,true),render(true,false,true)]){assert.equal(html.includes('inert-name'),false);assert.equal(html.includes('UNKNOWN'),false);}const html=render(true);assert.ok(html.includes('inert-name'));assert.equal(html.includes('<img inert-name>'),false);assert.equal(html.includes('href='),false);assert.ok(html.includes('Quadro de produção'));});

test('physical display distinguishes SQL absence from literal JSON null without rewriting precision',()=>{
  assert.equal(formatarValorEspelho(null),'Sem valor (SQL NULL)');
  for(const raw of ['null','9007199254740993','0.123456789012345678901','1e999',' {"n":9007199254740993} '])assert.equal(formatarValorEspelho(raw),raw);
  assert.equal(formatarValorEspelho(''),'""');assert.equal(formatarValorEspelho(0),'0');assert.equal(formatarValorEspelho(false),'false');
  const html=renderToStaticMarkup(React.createElement(ProducaoEspelhoView,{data:decodificarConsultaEspelho(dto()),autorizado:true,error:false,loading:false,fetching:false,identityKey:'x',atualizar:()=>{}}));
  assert.ok(html.includes('Sem orçamento'));
});
test('presenter identifies production source and reading time without claiming global source freshness',()=>{
  const data=decodificarConsultaEspelho(dto());
  const html=renderToStaticMarkup(React.createElement(ProducaoEspelhoView,{data,autorizado:true,error:false,loading:false,fetching:false,identityKey:'x',atualizar:()=>{}}));
  for(const label of ['Fonte: Controle de Produção','Momento da leitura:',instant,'Atualização global da fonte não confirmada.','Leituras independentes; consistência entre coleções não comprovada.','Alterações continuam no sistema de produção.'])assert.ok(html.includes(label),label);
  assert.equal(html.includes('Atualização global da fonte: '+instant),false);
});
