import test from 'node:test';
import assert from 'node:assert/strict';
import type {SupabaseClient} from '@supabase/supabase-js';
import {criarCrmEspelho,obterAcessoEspelho,revalidarAcessoEspelho,resolverEscopoEspelho,pedidoNoEscopoEspelho,type SnapshotEspelho} from '../../api/_lib/producao-espelho-acesso.js';
const uid='00000000-0000-4000-8000-000000000001',vid='00000000-0000-4000-8000-000000000002',other='00000000-0000-4000-8000-000000000003';
function fixture(){const state={user:uid,profile:{id:uid,role:'vendor',approved_at:'2026-10-02T09:00:00Z',vendor_id:vid} as Record<string,unknown>,papel:true as unknown,override:undefined as unknown,errorTable:'',vendors:[{id:vid,key:'ANA',name:'Ana Doe'}]};const reads:string[]=[];const crm={auth:{async getUser(){return {data:{user:{id:state.user}},error:null};}},from(table:string){reads.push(table);const conditions:Array<[string,unknown]>=[];const q={select:()=>q,eq(k:string,v:unknown){conditions.push([k,v]);return q;},async maybeSingle(){let data:unknown=null,error:unknown=state.errorTable===table?Error('PRIVATE'):null;if(table==='user_profiles')data=state.profile;if(table==='role_permissions')data={permissions:{'menu.producao_fabrica':state.papel}};if(table==='controle_permissoes_usuario')data=state.override===undefined?null:{permitido:state.override};if(table==='vendors'){const rows=state.vendors.filter(r=>conditions.every(([k,v])=>r[k as keyof typeof r]===v));if(rows.length>1)error=Error('ambiguous');data=rows[0]??null;}return {data,error};}};return q;}} as unknown as SupabaseClient;return {state,reads,crm};}
async function snapshot(f:ReturnType<typeof fixture>){const a=await obterAcessoEspelho(f.crm,'synthetic');assert.equal(a.ok,true);if(!a.ok)throw Error('denied');return a.snapshot;}
test('private CRM config pins destination, rejects wrong/fallback config and never initializes without explicit inputs',()=>{let calls=0;const fake={} as SupabaseClient;const create=(url:string,key:string,options:unknown)=>{calls++;assert.equal(url,'https://flwbeevtvjiouxdjmziv.supabase.co');assert.equal(key,'sb_secret_'+'synthetic'.repeat(5));assert.deepEqual(options,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});return fake;};assert.equal(criarCrmEspelho({SUPABASE_URL:'https://flwbeevtvjiouxdjmziv.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'sb_secret_'+'synthetic'.repeat(5)},create),fake);assert.equal(calls,1);for(const bad of [{},{SUPABASE_URL:'https://other.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'sb_secret_'+'x'.repeat(40)},{VITE_SUPABASE_URL:'https://flwbeevtvjiouxdjmziv.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'sb_secret_'+'x'.repeat(40)}])assert.throws(()=>criarCrmEspelho(bad,create),/producao_indisponivel/);assert.equal(calls,1);});
test('approval helper remains legacy while fresh factory snapshot preserves vendor UUID and exact capability',async()=>{const f=fixture(),s=await snapshot(f);assert.equal(s.vendorId,vid);assert.equal(s.userId,uid);for(const override of [false,'true',null]){f.state.override=override;assert.equal((await obterAcessoEspelho(f.crm,'synthetic')).ok,false);}f.state.override=undefined;f.state.papel=false;assert.equal((await obterAcessoEspelho(f.crm,'synthetic')).ok,false);f.state.override=true;assert.equal((await obterAcessoEspelho(f.crm,'synthetic')).ok,true);});
test('unknown/unapproved/mismatched/malformed profiles and lookup errors deny before scope',async()=>{for(const change of [{role:'consultor'},{approved_at:null},{id:other},{vendor_id:123},{vendor_id:'bad'}]){const f=fixture();Object.assign(f.state.profile,change);assert.equal((await obterAcessoEspelho(f.crm,'synthetic')).ok,false);assert.equal(f.reads.includes('vendors'),false);}for(const table of ['user_profiles','role_permissions','controle_permissoes_usuario']){const f=fixture();f.state.errorTable=table;assert.equal((await obterAcessoEspelho(f.crm,'synthetic')).ok,false);}});
test('global privileged scope never reads vendors or parents; restricted only current CRM identity and exact two canonical slots',async()=>{const f=fixture();const s=await snapshot(f);const scope=await resolverEscopoEspelho(f.crm,s);assert.deepEqual(scope.vendedores,['ANA','Ana Doe']);assert.equal(pedidoNoEscopoEspelho({vendedor:'OTHER',vendedor_2:'ANA'},scope),true);for(const value of ['ANA-extra','ana',' Ana Doe ',null])assert.equal(pedidoNoEscopoEspelho({vendedor:value,vendedor_2:null},scope),false);for(const role of ['admin','financeiro']){const g=fixture();g.state.profile.role=role;const global=await resolverEscopoEspelho(g.crm,await snapshot(g));assert.equal(global.vendedores,null);assert.equal(g.reads.includes('vendors'),false);}});
test('restricted missing/ambiguous mapping fails closed, never empty successful scope or global upgrade',async()=>{for(const mode of ['null','missing','ambiguous','error']){const f=fixture();if(mode==='null')f.state.profile.vendor_id=null;const s=await snapshot(f);if(mode==='missing')f.state.vendors=[];if(mode==='ambiguous')f.state.vendors.push({id:other,key:'OTHER',name:'ANA'});if(mode==='error')f.state.errorTable='vendors';await assert.rejects(resolverEscopoEspelho(f.crm,s),/sem_escopo|producao_indisponivel/);}});
test('final UUID/role/approval/identity/capability changes revoke factory access without using numeric legacy vendor result',async()=>{for(const change of [{vendor_id:other},{role:'admin'},{approved_at:'changed'},{id:other}]){const f=fixture(),s=await snapshot(f);Object.assign(f.state.profile,change);assert.equal((await revalidarAcessoEspelho(f.crm,'synthetic',s)).ok,false);}const f=fixture(),s=await snapshot(f);f.state.override=false;assert.equal((await revalidarAcessoEspelho(f.crm,'synthetic',s)).ok,false);assert.equal((await revalidarAcessoEspelho(fixture().crm,'synthetic',s)).ok,true);});
