import test from 'node:test';
import assert from 'node:assert/strict';
import type {SupabaseClient} from '@supabase/supabase-js';
import type {VercelRequest,VercelResponse} from '@vercel/node';
import {criarHandlerControleProducao} from '../../api/controle-producao.js';
import type {ConsultaQuadroEspelho} from './producao-espelho-consulta';
import type {lerProducaoEspelho} from '../../api/_lib/producao-espelho-reader.js';
const uid='00000000-0000-4000-8000-000000000001',vid='00000000-0000-4000-8000-000000000002',other='00000000-0000-4000-8000-000000000003',stamp='2026-10-02T09:00:00Z';
const empty={origem:'app2',fonte:'controle-producao-live',consultadoEm:stamp,atualizadoEm:null,sincronizadoEm:null,parcial:false,aviso:'Leituras independentes; consistência entre coleções não comprovada.',consistency:'crossread_unproved',complete:{cards:true,historico:true,logistica:true,setores:true,checklists:true},totals:{cards:0,historico:0,logistica:0,setores:0,checklists:0},dados:{cards:[],kpis:{total:0,excluidos:0,ativos:0,entregues:0,cancelados:0,pedidosUnicos:0},porEtapa:{},porSetor:{}}};
const light={...empty,visao:'quadro-v1',parcial:true,complete:{cards:true,historico:false,logistica:false,setores:false,checklists:false},totals:{cards:0,historico:null,logistica:null,setores:null,checklists:null},dados:{...empty.dados,porSetor:null}};
function fixture(){const state={user:uid,profile:{id:uid,role:'admin',approved_at:stamp,vendor_id:vid} as Record<string,unknown>,papel:true as unknown,override:undefined as unknown,errorTable:'',vendors:[{id:vid,key:'ANA',name:'Ana Doe'}]};const reads:string[]=[];const crm={auth:{async getUser(){return {data:{user:{id:state.user}},error:null};}},from(table:string){reads.push(table);const filters:Array<[string,unknown]>=[];const q={select:()=>q,eq(k:string,v:unknown){filters.push([k,v]);return q;},async maybeSingle(){let data:unknown=null,error:unknown=state.errorTable===table?Error('PRIVATE'):null;if(table==='user_profiles')data=state.profile;if(table==='role_permissions')data={permissions:{'menu.producao_fabrica':state.papel}};if(table==='controle_permissoes_usuario')data=state.override===undefined?null:{permitido:state.override};if(table==='vendors'){const rows=state.vendors.filter(vendor=>filters.every(([k,v])=>vendor[k as keyof typeof vendor]===v));data=rows[0]??null;if(rows.length>1)error=Error('PRIVATE ambiguous');}return {data,error};}};return q;}} as unknown as SupabaseClient;return {state,reads,crm};}
async function call(f=fixture(),request:Partial<VercelRequest>={},output:unknown=empty,after?:()=>void,deadlineMs?:number){let reads=0,crms=0,status=0,emits=0;let body:unknown;const headers:Record<string,unknown>={};const res={setHeader(k:string,v:unknown){headers[k]=v;return res;},status(n:number){status=n;return res;},json(v:unknown){body=v;emits++;return res;}} as unknown as VercelResponse;const handler=criarHandlerControleProducao({crm:()=>{crms++;return f.crm;},lerFabrica:(async(scope)=>{reads++;assert.equal(scope.userId,uid);if(deadlineMs)await new Promise(r=>setTimeout(r,20));after?.();if(output instanceof Error)throw output;return output;}) as typeof lerProducaoEspelho,deadlineMs,...{lerQuadro:async()=>{reads++;after?.();return output as ConsultaQuadroEspelho;}}});await handler({method:'GET',query:{origem:'app2'},headers:{authorization:'Bearer synthetic'},...request} as VercelRequest,res);return {status,body:body as Record<string,unknown>,headers,reads,crms,get emits(){return emits;}};}
test('only fixed factory GET projects private metadata/no-store, global does not read vendors',async()=>{const f=fixture(),result=await call(f);assert.equal(result.status,200);assert.equal(result.headers['Cache-Control'],'no-store');assert.equal(result.headers.Vary,'Authorization');assert.equal(result.body.fonte,'controle-producao-live');assert.equal(result.reads,1);assert.equal(f.reads.includes('vendors'),false);});
test('wrong methods/origin/query/body/auth rejected before private client or source, no internal fallback',async()=>{for(const [request,status] of [[{method:'POST'},405],[{query:{origem:'controle-interno'}},400],[{query:{origem:['app2']}},400],[{query:{origem:'app2',extra:'x'}},400],[{query:Object.create({origem:'app2'})},400],[{body:{}},400],[{headers:{}},401],[{headers:{authorization:'Bearer x y'}},401]] as const){const r=await call(fixture(),request as Partial<VercelRequest>);assert.equal(r.status,status);assert.equal(r.crms,0);assert.equal(r.reads,0);}const r=await call(fixture(),{method:'OPTIONS'});assert.equal(r.headers.Allow,'GET');});
test('approval/capability/override false even admin/known roles and lookup failures reject before source',async()=>{for(const [change,status] of [[{role:'consultor'},403],[{approved_at:null},403],[{vendor_id:'invalid'},403],[{id:other},403]] as const){const f=fixture();Object.assign(f.state.profile,change);const r=await call(f);assert.equal(r.status,status);assert.equal(r.reads,0);}for(const setting of ['papel','override'] as const){const f=fixture();f.state[setting]=false;const r=await call(f);assert.equal(r.status,403);assert.equal(r.reads,0);}for(const table of ['user_profiles','role_permissions','controle_permissoes_usuario']){const f=fixture();f.state.errorTable=table;const r=await call(f);assert.equal(r.status,500);assert.equal(r.reads,0);assert.equal(JSON.stringify(r.body).includes('PRIVATE'),false);}});
test('fresh profile UUID/approval/role/user and permission changes while SELECT is pending cannot emit data',async()=>{for(const change of [{vendor_id:other},{role:'financeiro'},{approved_at:'changed'},{id:other}]){const f=fixture();const r=await call(f,{},empty,()=>Object.assign(f.state.profile,change));assert.equal(r.status,403);assert.equal(r.body.dados,undefined);}for(const mutate of [(f:ReturnType<typeof fixture>)=>{f.state.override=false;},(f:ReturnType<typeof fixture>)=>{f.state.user=other;}]){const f=fixture();const r=await call(f,{},empty,()=>mutate(f));assert.equal(r.status,403);assert.equal(r.body.dados,undefined);}});
test('source errors/partial/incoherent completeness totals fail integral503 without private details',async()=>{for(const output of [Error('PRIVATE SOURCE URL KEY'),{...empty,parcial:true},{...empty,totals:{...empty.totals,cards:573}}]){const r=await call(fixture(),{},output);assert.equal(r.status,503);assert.deepEqual(r.body,{error:'producao_indisponivel'});assert.equal(r.reads,1);}});
test('bounded endpoint timeout masks late source completion and never emits twice',async()=>{const r=await call(fixture(),{},empty,undefined,5);assert.equal(r.status,503);await new Promise(resolve=>setTimeout(resolve,30));assert.equal(r.emits,1);assert.equal(r.body.dados,undefined);});

test('API recomputes derived KPI safely while completeness counts remain strict',async()=>{const r=await call(fixture(),{},{...empty,dados:{...empty.dados,kpis:{...empty.dados.kpis,total:999},porEtapa:{UNKNOWN:999}}});assert.equal(r.status,200);assert.equal((r.body.dados as typeof empty.dados).kpis.total,0);assert.deepEqual((r.body.dados as typeof empty.dados).porEtapa,{});});

for(const mode of ['key','name','removed','collision','lookup-error'] as const)test(`restricted canonical ${mode} change during source await discards the entire result`,async()=>{
  const f=fixture();f.state.profile.role='vendor';
  const r=await call(f,{},empty,()=>{
    if(mode==='key')f.state.vendors[0].key='OTHER';
    if(mode==='name')f.state.vendors[0].name='Other Name';
    if(mode==='removed')f.state.vendors=[];
    if(mode==='collision')f.state.vendors.push({id:other,key:'OTHER',name:'ANA'});
    if(mode==='lookup-error')f.state.errorTable='vendors';
  });
  assert.equal(r.status,mode==='key'||mode==='name'?403:503);assert.equal(r.body.dados,undefined);assert.equal(r.emits,1);assert.equal(r.reads,1);assert.equal(JSON.stringify(r.body).includes('PRIVATE'),false);
});
test('unchanged restricted mapping remains authorized; both global roles skip final vendors lookup',async()=>{
  const f=fixture();f.state.profile.role='vendor';assert.equal((await call(f)).status,200);
  for(const role of ['admin','financeiro']){const g=fixture();g.state.profile.role=role;const r=await call(g,{},empty,()=>{g.state.vendors=[];g.state.errorTable='vendors';});assert.equal(r.status,200);assert.equal(g.reads.includes('vendors'),false);}
});

test('opt-in light GET remains separately validated and reauthorizes before returning data',async()=>{const req={query:{origem:'app2',visao:'quadro-v1'}};const r=await call(fixture(),req,light);assert.equal(r.status,200);assert.deepEqual(r.body,light);assert.equal(r.reads,1);const bad=await call(fixture(),req,empty);assert.equal(bad.status,503);const f=fixture();const revoked=await call(f,req,light,()=>{f.state.override=false;});assert.equal(revoked.status,403);assert.equal(revoked.body.dados,undefined);});
test('unknown or repeated view selectors reject before any clients or source reads',async()=>{for(const visao of ['','completo','QUADRO-V1',['quadro-v1']]){const r=await call(fixture(),{query:{origem:'app2',visao}} as Partial<VercelRequest>,light);assert.equal(r.status,400);assert.equal(r.crms,0);assert.equal(r.reads,0);}});
