import test from 'node:test';
import assert from 'node:assert/strict';
import {CHAVE_PRODUCAO_FABRICA,canComExcecaoFabrica,permissaoProducaoFabrica,decidirRotaProducaoFabrica,type EstadoPermissoesFabrica} from './producao-espelho-permissoes';
const ready:EstadoPermissoesFabrica={userId:'u1',profileId:'u1',role:'admin',approvedAt:'approved',authLoading:false,profileError:false,permissionsUserId:'u1',loading:false,error:false,papel:true,override:undefined};
test('factory exact ready capability allows known roles without admin fallback, override false wins',()=>{assert.equal(CHAVE_PRODUCAO_FABRICA,'menu.producao_fabrica');for(const role of ['admin','financeiro','vendor','mapa','marketing','visualizador']){assert.equal(permissaoProducaoFabrica({...ready,role}),true);assert.equal(permissaoProducaoFabrica({...ready,role,override:false}),false);}for(const papel of [undefined,null,false,'true',1])assert.equal(permissaoProducaoFabrica({...ready,papel}),false);assert.equal(permissaoProducaoFabrica({...ready,papel:false,override:true}),true);});
test('loading/errors/stale identity/unapproved/unknown role close the factory only',()=>{for(const change of [{authLoading:true},{profileError:true},{loading:true},{error:true},{userId:null},{profileId:'other'},{permissionsUserId:'other'},{approvedAt:null},{role:'consultor'},{role:'pending'},{override:'true'}])assert.equal(permissaoProducaoFabrica({...ready,...change}),false);assert.equal(decidirRotaProducaoFabrica('/whatsapp',ready),'unrelated');assert.equal(decidirRotaProducaoFabrica('/controle/financeiro',ready),'unrelated');});
test('factory Router matching gates direct/encoded/case/trailing paths and never parent or prefix spoof',()=>{for(const p of ['/controle/producao/fabrica','/CONTROLE/producao/fabrica/','/controle/%70roducao/fabrica'])assert.equal(decidirRotaProducaoFabrica(p,ready),'allow');for(const p of ['/controle/producao/fabrica-extra','/controle/producao/fabrica/outro','/controle%2fproducao/fabrica','/controle'])assert.equal(decidirRotaProducaoFabrica(p,ready),'unrelated');assert.equal(decidirRotaProducaoFabrica('/controle/producao/fabrica',{...ready,loading:true}),'loading');assert.equal(decidirRotaProducaoFabrica('/controle/producao/fabrica',{...ready,error:true}),'error');assert.equal(decidirRotaProducaoFabrica('/controle/producao/fabrica',{...ready,override:false}),'deny');});

test('only exact factory key uses closed gate; every legacy key keeps its original callback result',()=>{let calls=0;const legacy=()=>{calls++;return true;};assert.equal(canComExcecaoFabrica('menu.whatsapp',{...ready,error:true},legacy),true);assert.equal(calls,1);assert.equal(canComExcecaoFabrica('menu.financeiro',{...ready,error:true},()=>false),false);assert.equal(canComExcecaoFabrica('menu.producao_fabrica',{...ready,error:true},legacy),false);assert.equal(calls,1);assert.equal(canComExcecaoFabrica('menu.producao_fabrica-extra',{...ready,error:true},legacy),true);assert.equal(calls,2);});
