import test from 'node:test';
import assert from 'node:assert/strict';
import type {VercelRequest,VercelResponse} from '@vercel/node';
import {criarHandlerControleVendas,type DependenciasHandlerVendas} from '../controle-vendas.js';
import type {SnapshotControleVendas} from './controle-vendas-acesso.js';
import {autorizarControleVendas,revalidarControleVendas} from './controle-vendas-acesso.js';
import type {SupabaseClient} from '@supabase/supabase-js';
const snapshot:SnapshotControleVendas={userId:'11111111-1111-4111-8111-111111111111',role:'admin',approvedAt:'approved',vendorId:null,vendedores:null};
const data={data:[],vendedores:[],escopo:{global:true,vendedorNome:null}};
function response(){const output={status:0,body:undefined as unknown,headers:new Map<string,unknown>()};const res={setHeader:(key:string,value:unknown)=>{output.headers.set(key,value);return res;},status:(code:number)=>{output.status=code;return res;},json:(value:unknown)=>{output.body=value;return res;},end:()=>res};return {output,res:res as unknown as VercelResponse};}
function request(extra:Record<string,unknown>={}){return {method:'GET',headers:{authorization:'Bearer token'},query:{inicio:'2026-01-01',fim:'2026-12-31'},...extra} as unknown as VercelRequest;}
function deps(extra:Partial<DependenciasHandlerVendas>={}):DependenciasHandlerVendas{return {autorizar:async()=>({ok:true,snapshot}),revalidar:async()=>({ok:true,snapshot}),ler:async()=>data,...extra};}
test('GET sends only the final authorized report with private cache headers',async()=>{const {output,res}=response();await criarHandlerControleVendas(deps())(request(),res);assert.equal(output.status,200);assert.deepEqual(output.body,data);assert.match(String(output.headers.get('Cache-Control')),/no-store/);assert.equal(output.headers.get('Vary'),'Authorization');});
test('denied identities and invalid query never read the source',async()=>{let reads=0;const ler=async()=>{reads++;return data;};const denied=response();await criarHandlerControleVendas(deps({autorizar:async()=>({ok:false,status:403,error:'sem_permissao'}),ler}))(request(),denied.res);assert.equal(denied.output.status,403);const invalid=response();await criarHandlerControleVendas(deps({ler}))(request({query:{inicio:'2026-02-30',fim:'2026-12-31'}}),invalid.res);assert.equal(invalid.output.status,400);assert.equal(reads,0);});
test('permission revoked while source was loading suppresses the entire result',async()=>{const {output,res}=response();await criarHandlerControleVendas(deps({revalidar:async()=>({ok:false,status:403,error:'sem_permissao'})}))(request(),res);assert.equal(output.status,403);assert.deepEqual(output.body,{error:'sem_permissao'});});
test('provider failure is sanitized and deadline aborts the underlying read',async()=>{const failure=response();await criarHandlerControleVendas(deps({ler:async()=>{throw new Error('provider secret');}}))(request(),failure.res);assert.equal(failure.output.status,502);assert.deepEqual(failure.output.body,{error:'controle_indisponivel'});let aborted=false;const deadline=response();await criarHandlerControleVendas(deps({timeoutMs:5,ler:async(_query,_snapshot,signal)=>new Promise((_resolve,reject)=>{signal.addEventListener('abort',()=>{aborted=true;reject(signal.reason);},{once:true});})}))(request(),deadline.res);assert.equal(aborted,true);assert.equal(deadline.output.status,504);assert.deepEqual(deadline.output.body,{error:'controle_indisponivel'});});
test('method and Origin rejection happen before authentication or source access',async()=>{let calls=0;const opts=deps({autorizar:async()=>{calls++;return {ok:true,snapshot};}});for(const [req,status] of [[request({method:'POST'}),405],[request({headers:{origin:'https://outside.invalid',authorization:'Bearer token'}}),400]] as const){const {output,res}=response();await criarHandlerControleVendas(opts)(req,res);assert.equal(output.status,status);}assert.equal(calls,0);});
test('a real fresh capability read revokes a source result that completed after a permission change',async()=>{
  let permitido=true,profileReads=0;
  const crm={auth:{getUser:async()=>({data:{user:{id:snapshot.userId}},error:null})},from:(table:string)=>{const q={select:()=>q,eq:()=>q,maybeSingle:async()=>{if(table==='user_profiles')profileReads++;return {data:table==='role_permissions'?{permissions:{'menu.financeiro':permitido}}:{id:snapshot.userId,role:'admin',approved_at:snapshot.approvedAt,vendor_id:null},error:null};}};return q;}} as unknown as SupabaseClient;
  const accessDeps={crm,resolver:async()=>({userId:snapshot.userId,role:'admin',vendedores:null})};
  const {output,res}=response();await criarHandlerControleVendas(deps({autorizar:auth=>autorizarControleVendas(auth,accessDeps),revalidar:(auth,old)=>revalidarControleVendas(auth,old,accessDeps),ler:async()=>{permitido=false;return data;}}))(request(),res);
  assert.equal(output.status,403);assert.deepEqual(output.body,{error:'sem_permissao'});assert.equal(profileReads,4);
});
