import type { ModeloCandidato, OrcamentoAISnapshot } from '../types'

export const compacta03Master150500Mono: ModeloCandidato = {
  id: 2607,
  basename: 'Compacta 03 Master - 150500 - 4000 - 4000 com ensacadeira',
  linha: 'COMPACTA_03',
  master: true,
  voltagem: 'monofasico',
  producaoKgH: 150500,
  armazenamentoKg: 4000,
  itens: [
    { catalogoId: 1, nome: 'TRANSPORTADOR HELICOIDAL 160 X 3,5 M', quantidade: 1, valorUnitario: 5795 },
    { catalogoId: 2, nome: 'TRITURADOR DE GRÃOS 10 CV', quantidade: 1, valorUnitario: 14708.1 },
    { catalogoId: 3, nome: 'TRANSPORTADOR HELICOIDAL 160 X 6,0 M', quantidade: 1, valorUnitario: 7470 },
    { catalogoId: 4, nome: 'CAIXA DE PICADOS', quantidade: 1, valorUnitario: 19900.1 },
    { catalogoId: 5, nome: 'CAÇAMBA DE PESAGEM 1900 LITROS', quantidade: 1, valorUnitario: 17306 },
    { catalogoId: 6, nome: 'TRANSPORTADOR HELICOIDAL 210 X 4,0 M', quantidade: 1, valorUnitario: 7564 },
    { catalogoId: 7, nome: 'MISTURADOR HORIZONTAL 900 LITROS (500 KG)', quantidade: 1, valorUnitario: 53514 },
    { catalogoId: 8, nome: 'TRANSPORTADOR HELICOIDAL 210 X 5,0 M', quantidade: 1, valorUnitario: 8121 },
    { catalogoId: 9, nome: 'CAIXA DE RAÇÃO PRONTA', quantidade: 1, valorUnitario: 17906 },
    { catalogoId: 10, nome: 'ENSACADEIRA SEMI AUTOMATICA', quantidade: 1, valorUnitario: 26400 },
  ],
  motores: [
    { descricao: 'Motor 1,5 CV 4 polos', cv: 1.5, polos: 4, valor: 2536, incluso: false },
    { descricao: 'Motor 15 CV 2 polos', cv: 15, polos: 2, valor: 7994, incluso: false },
    { descricao: 'Motor 3 CV 4 polos', cv: 3, polos: 4, valor: 3786, incluso: false },
    { descricao: 'Motorredutor 2 CV', cv: 2, valor: 0, incluso: true },
    { descricao: 'Motor 3 CV 4 polos', cv: 3, polos: 4, valor: 3786, incluso: false },
    { descricao: 'Motorredutor 7,5 CV', cv: 7.5, valor: 0, incluso: true },
    { descricao: 'Motor 5 CV 4 polos', cv: 5, polos: 4, valor: 5266, incluso: false },
    { descricao: 'Motorredutor 1,5 CV', cv: 1.5, valor: 0, incluso: true },
  ],
  acessorios: {
    mode: 'fixo',
    valor: 12154,
    items: [
      'Torres de fixação para chupins 210',
      'Bocas de alimentação para chupins 210',
      'Bocas de descarga para chupins 210',
      'Torres de fixação para chupins 160',
      'Bocas de alimentação para chupins 160',
      'Bocas de descarga para chupins 160',
      'Funil de alimentação moinho',
      'Base do moinho',
      'Boca de descarga do moinho',
      'Descargas duas vias',
    ],
    source: 'modelo',
  },
  componentes: [{ nome: 'Balança Eletrônica', valor: 8728 }],
  fotoUrl: 'https://example.invalid/compacta-03-master.jpg',
}

export const emptyQuoteSnapshot: OrcamentoAISnapshot = {
  orcamentoId: null,
  cliente: { nome: '' },
  modelo: null,
  itens: [],
  motores: [],
  acessorios: null,
  componentes: [],
  voltagem: null,
  fotoPrincipalUrl: null,
  condicoes: {
    formaPagamento: 'A combinar',
    prazoDias: 60,
    prazoTipo: 'uteis',
    freteTipo: 'FOB',
    freteTexto: 'Frete por conta do cliente',
    validadeDias: 10,
    observacoes: '',
  },
}
