-- ============================================================================
-- Guia do Vendedor — seed de FONTES e IMAGENS
-- Gerado em 2026-08-03 a partir da auditoria do guia.html antigo.
--
-- Nenhuma imagem nasce 'verificada': o schema exige autor + licença +
-- verificada_em + aprovada_por, e ainda não existe aprovador nomeado na
-- Branorte. Todas entram 'pendente' (aparecem com selo) ou 'reprovada' (não
-- aparecem — a UI cai no fallback).
-- ============================================================================

insert into public.guia_fontes (chave, titulo, organizacao, tipo, observacao) values
  ('embrapa-suinos-aves', 'Embrapa Suínos e Aves — publicações técnicas', 'Embrapa Suínos e Aves (Concórdia/SC)', 'embrapa', 'Edição e URL específicas a confirmar por publicação citada.'),
  ('embrapa-gado-corte', 'Embrapa Gado de Corte — publicações técnicas', 'Embrapa Gado de Corte (Campo Grande/MS)', 'embrapa', 'Edição e URL específicas a confirmar por publicação citada.'),
  ('embrapa-gado-leite', 'Embrapa Gado de Leite — publicações técnicas', 'Embrapa Gado de Leite (Juiz de Fora/MG)', 'embrapa', 'Edição e URL específicas a confirmar por publicação citada.'),
  ('embrapa-caprinos-ovinos', 'Embrapa Caprinos e Ovinos — publicações técnicas', 'Embrapa Caprinos e Ovinos (Sobral/CE)', 'embrapa', 'Edição e URL específicas a confirmar por publicação citada.'),
  ('embrapa-semiarido', 'Embrapa Semiárido — palma forrageira e convivência com a seca', 'Embrapa Semiárido (Petrolina/PE)', 'embrapa', 'Edição e URL específicas a confirmar.'),
  ('rostagno-tabelas', 'Tabelas Brasileiras para Aves e Suínos — composição de alimentos e exigências nutricionais', 'UFV — Rostagno, H. S. et al.', 'literatura', 'REFERÊNCIA PRINCIPAL de composição e inclusão. Edição e ano a confirmar com o nutricionista antes de publicar qualquer faixa como fechada.'),
  ('mapa-alimentacao-animal', 'Legislação de produtos destinados à alimentação animal', 'MAPA — Ministério da Agricultura e Pecuária', 'legislacao', 'Instruções normativas aplicáveis a fabricação, rotulagem, aditivos e boas práticas. Número da IN a confirmar por assunto.'),
  ('abcz', 'Padrões raciais das raças zebuínas', 'ABCZ — Associação Brasileira dos Criadores de Zebu', 'associacao_raca', 'Fonte oficial para Nelore, Guzerá, Brahman, Gir, Tabapuã.'),
  ('girolando', 'Padrão racial e graus de sangue do Girolando', 'Associação Brasileira dos Criadores de Girolando', 'associacao_raca', 'Necessária para fechar a definição de grau de sangue e a participação do Girolando na produção nacional.'),
  ('abccan', 'Padrão racial do Canchim', 'ABCCAN — Associação Brasileira dos Criadores de Canchim', 'associacao_raca', null),
  ('abcb-angus', 'Padrão racial e programas de carne Angus', 'Associação Brasileira de Angus', 'associacao_raca', null),
  ('manual-cobb', 'Manual de manejo e objetivos de desempenho — Cobb', 'Cobb-Vantress', 'manual_linhagem', 'OBRIGATÓRIO: qualquer número de conversão precisa citar edição, ano, sexo, idade e peso-alvo. Os valores do guia antigo (1,97/2,16 + "no campo 1,5") eram contraditórios e foram removidos.'),
  ('manual-ross', 'Broiler Performance Objectives / Manual de manejo — Ross', 'Aviagen', 'manual_linhagem', 'OBRIGATÓRIO: edição, ano, sexo, idade e peso-alvo. Os valores do guia antigo (1,89/2,01) estavam sem contexto e foram removidos.'),
  ('manual-hyline', 'Commercial Layer Management Guide — Hy-Line Brown / W-36', 'Hy-Line International', 'manual_linhagem', 'Ovos por ave alojada e consumo dependem da idade final considerada. Sem isso o número não vale.'),
  ('manual-isa', 'Product Guide — ISA Brown', 'ISA / Hendrix Genetics', 'manual_linhagem', null),
  ('manual-lohmann', 'Layer Management Guide — Lohmann Brown / LSL', 'Lohmann Breeders (EW Group)', 'manual_linhagem', null),
  ('branorte-catalogo', 'Catálogo de equipamentos e capacidades da linha Branorte', 'Branorte', 'branorte', 'Base do bloco "o que a Branorte atende". Conferido no catálogo do CRM (precos_branorte / orcamento_modelos) em 03/08/2026: 0 itens de peletização ou extrusão. Linha Compacta JR 30 kg/h a Compacta 03 500 kg/h.'),
  ('branorte-engenharia', 'Engenharia Branorte — comportamento de materiais no equipamento', 'Branorte', 'branorte', 'PENDENTE. Densidade, abrasividade, formação de ponte, corrosão e misturador indicado precisam do aval da engenharia. Os valores atuais são inferência de literatura e prática, não medição.')
on conflict (chave) do update set titulo = excluded.titulo, organizacao = excluded.organizacao, tipo = excluded.tipo, observacao = excluded.observacao;

insert into public.guia_imagens (slug, arquivo_url, alt, legenda, autor, licenca, fonte_url, url_original, status, identifica_item, verificada_em, aprovada_por, motivo_reprovacao) values
  ('nelore', '/img/guia/nelore.webp', 'Touro Nelore branco de perfil, com cupim e barbela marcados, em pista de exposição', null, 'Eduardo Ferraz Pacheco de Castro e Sebastião de Oliveira', 'CC0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('angus', '/img/guia/angus.webp', 'Bovinos Angus pretos, sem cupim, em pastagem', null, 'Bill Tarpenning (USDA)', 'Domínio público', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('brahman', '/img/guia/brahman.webp', 'Touro Brahman cinza de perfil, com cupim proeminente e orelhas grandes pendentes', null, 'José Reynaldo da Fonseca', 'CC BY 2.5', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('senepol', '/img/guia/senepol.webp', 'Touro Senepol vermelho de perfil, pelo curto e sem cupim, em pastagem', null, 'Buenoperez', 'Domínio público', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('canchim', '/img/guia/canchim.webp', 'Touro Canchim de pelagem creme, de perfil, em pista de exposição', 'Imagem ilustrativa: representa o tipo/categoria, não serve como prova de identidade racial. Substituir por foto do acervo Branorte quando disponível.', 'José Reynaldo da Fonseca (REFON)', 'CC BY 2.5', 'https://commons.wikimedia.org/', null, 'pendente', false, null, null, null),
  ('guzera', '/img/guia/guzera.webp', 'Touro Guzerá cinza de perfil, com chifres em lira e cupim', null, 'José Reynaldo da Fonseca (REFON)', 'CC BY 2.5', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('confinamento', '/img/guia/confinamento.webp', 'Touro Wagyu de pelagem preta, de corpo inteiro, em pastagem', null, 'Fernando Hartwig', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('girolando', '/img/guia/girolando.webp', 'Vaca mestiça Holandês x Gir, pelagem preta e branca, de perfil em pastagem', 'Imagem ilustrativa: representa o tipo/categoria, não serve como prova de identidade racial. Substituir por foto do acervo Branorte quando disponível.', 'teliocampos', 'Domínio público', 'https://commons.wikimedia.org/', null, 'pendente', false, null, null, null),
  ('holandes', '/img/guia/holandes.webp', 'Vaca Holandesa preta e branca de perfil, em pastagem', null, 'Hayden Soloviev', 'CC BY 4.0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('gir-leiteiro', '/img/guia/gir-leiteiro.webp', 'Bovino Gir de perfil, pelagem vermelha malhada, orelhas longas e chifres voltados para trás', null, 'Chovatiyahiren', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('jersey', '/img/guia/jersey.webp', 'Vaca Jersey de pelagem parda clara, de porte pequeno, em instalação de ordenha', null, 'Jennifer Dickert', 'CC BY 2.0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('pardo-suico', '/img/guia/pardo-suico.webp', 'Bovino Pardo-Suíço de pelagem parda uniforme, de perfil', null, 'Malcolm Morley', 'Domínio público', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('mestica-pasto', '/img/guia/mestica-pasto.webp', 'Vaca mestiça leiteira em pastagem tropical', 'Imagem ilustrativa: representa o tipo/categoria, não serve como prova de identidade racial. Substituir por foto do acervo Branorte quando disponível.', 'Fernando Gabriel de Melo Domingo', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/', null, 'pendente', false, null, null, null),
  ('isa-brown', '/img/guia/isa-brown.webp', 'Galinha poedeira de plumagem marrom em galpão comercial', 'Linhagens comerciais de aves não são visualmente distinguíveis entre si: Cobb e Ross são ambos frangos brancos de corte; ISA, Hy-Line e Lohmann Brown são todas poedeiras de plumagem marrom. Nenhuma foto — nem a oficial da genética — permite verificar a identidade. Esta imagem ilustra o TIPO de ave, não a linhagem.', 'Mercoaves', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/', null, 'pendente', false, null, null, null),
  ('lohmann-brown', '/img/guia/lohmann-brown.webp', 'Galinha poedeira de plumagem marrom-clara', 'Linhagens comerciais de aves não são visualmente distinguíveis entre si: Cobb e Ross são ambos frangos brancos de corte; ISA, Hy-Line e Lohmann Brown são todas poedeiras de plumagem marrom. Nenhuma foto — nem a oficial da genética — permite verificar a identidade. Esta imagem ilustra o TIPO de ave, não a linhagem.', 'Konstantin Nikiforov', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/', null, 'pendente', false, null, null, null),
  ('white-leghorn', '/img/guia/white-leghorn.webp', 'Galinha de plumagem branca e crista vermelha simples, tipo leve de postura', 'Linhagens comerciais de aves não são visualmente distinguíveis entre si: Cobb e Ross são ambos frangos brancos de corte; ISA, Hy-Line e Lohmann Brown são todas poedeiras de plumagem marrom. Nenhuma foto — nem a oficial da genética — permite verificar a identidade. Esta imagem ilustra o TIPO de ave, não a linhagem.', 'Bodlina', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/', null, 'pendente', false, null, null, null),
  ('pescoco-pelado', '/img/guia/pescoco-pelado.webp', 'Galo caipira de pescoço nu, criado a campo', 'Linhagens comerciais de aves não são visualmente distinguíveis entre si: Cobb e Ross são ambos frangos brancos de corte; ISA, Hy-Line e Lohmann Brown são todas poedeiras de plumagem marrom. Nenhuma foto — nem a oficial da genética — permite verificar a identidade. Esta imagem ilustra o TIPO de ave, não a linhagem.', 'Trigueiro martins', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/', null, 'pendente', false, null, null, null),
  ('paraiso-pedres', '/img/guia/paraiso-pedres.webp', 'Galinha de plumagem pedrês criada em sistema a campo', 'Linhagens comerciais de aves não são visualmente distinguíveis entre si: Cobb e Ross são ambos frangos brancos de corte; ISA, Hy-Line e Lohmann Brown são todas poedeiras de plumagem marrom. Nenhuma foto — nem a oficial da genética — permite verificar a identidade. Esta imagem ilustra o TIPO de ave, não a linhagem.', 'Thomas Kriese', 'CC BY 2.0', 'https://commons.wikimedia.org/', null, 'pendente', false, null, null, null),
  ('landrace', '/img/guia/landrace.webp', 'Suíno branco de corpo comprido com orelhas grandes caídas para frente', null, 'Dingar', 'Domínio público', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('large-white', '/img/guia/large-white.webp', 'Suíno branco com orelhas eretas e pernil cheio', null, 'Homoatrox', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('duroc', '/img/guia/duroc.webp', 'Suíno de pelagem vermelha, de corpo inteiro', null, 'Fabricio Cardenas', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('pietrain', '/img/guia/pietrain.webp', 'Suíno branco com manchas pretas e musculatura de pernil muito desenvolvida', null, 'Oleg Yunakov', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('suinos-terminacao', '/img/guia/suinos-terminacao.webp', 'Suínos brancos de terminação em baia de granja comercial', 'Imagem ilustrativa: representa o tipo/categoria, não serve como prova de identidade racial. Substituir por foto do acervo Branorte quando disponível.', 'Homoatrox', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/', null, 'pendente', false, null, null, null),
  ('milho', '/img/guia/milho.webp', 'Grãos de milho amarelo a granel', null, 'Miansari66', 'CC0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('sorgo', '/img/guia/sorgo.webp', 'Panícula e grãos de sorgo', null, 'Pethan', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('raspa-mandioca', '/img/guia/raspa-mandioca.webp', 'Raízes de mandioca', 'Imagem ilustrativa: representa o tipo/categoria, não serve como prova de identidade racial. Substituir por foto do acervo Branorte quando disponível.', 'Ken Wiegand', 'Domínio público', 'https://commons.wikimedia.org/', null, 'pendente', false, null, null, null),
  ('oleo-soja', '/img/guia/oleo-soja.webp', 'Óleo vegetal de soja', null, 'United Soybean Board', 'CC BY 2.0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('farelo-soja', '/img/guia/farelo-soja.webp', 'Farelo de soja moído', null, 'United Soybean Board', 'CC BY 2.0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('caroco-algodao', '/img/guia/caroco-algodao.webp', 'Caroços de algodão com línter', null, 'USDA', 'Domínio público', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('calcario-calcitico', '/img/guia/calcario-calcitico.webp', 'Rocha calcária moída', 'Imagem ilustrativa: representa o tipo/categoria, não serve como prova de identidade racial. Substituir por foto do acervo Branorte quando disponível.', 'Slknight', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/', null, 'pendente', false, null, null, null),
  ('sal-comum', '/img/guia/sal-comum.webp', 'Cristais de sal grosso (cloreto de sódio)', null, 'Glane23', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('ureia', '/img/guia/ureia.webp', 'Ureia em grânulos brancos', null, 'LHcheM', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('farelo-trigo', '/img/guia/farelo-trigo.webp', 'Farelo de trigo', null, 'Rasbak', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('silagem-milho', '/img/guia/silagem-milho.webp', 'Silagem armazenada em silo de superfície', 'Imagem ilustrativa: representa o tipo/categoria, não serve como prova de identidade racial. Substituir por foto do acervo Branorte quando disponível.', 'B. Grochowski', 'Domínio público', 'https://commons.wikimedia.org/', null, 'pendente', false, null, null, null),
  ('palma-forrageira', '/img/guia/palma-forrageira.webp', 'Plantio de palma forrageira (cacto Opuntia) no semiárido', null, 'YG01', 'CC BY 4.0', 'https://commons.wikimedia.org/', null, 'pendente', true, null, null, null),
  ('embrapa-051', null, 'Embrapa 051 (poedeira colonial) — sem foto verificada', null, null, null, null, null, 'reprovada', false, null, null, 'Foto genérica de galinha vermelha com pintinhos brancos, em pastagem. Não identifica a linhagem e a coloração dos pintinhos é incoerente com a genética descrita no card.'),
  ('embrapa-021', null, 'Embrapa 021 (frango de corte de crescimento lento) — sem foto verificada', null, null, null, null, null, 'reprovada', false, null, null, 'A foto mostra uma galinha adulta em gramado; o card trata de FRANGO DE CORTE. Item errado, além de genérica.'),
  ('cobb-500', null, 'Cobb 500 — sem foto verificada', null, null, null, null, null, 'reprovada', false, null, null, 'Foto genérica de frangos em galpão, creditada a "Animals Uncovered" — organização de ativismo animal. Impróprio para material comercial da Branorte, além de não identificar a linhagem.'),
  ('ross-308', null, 'Ross 308 — sem foto verificada', null, null, null, null, null, 'reprovada', false, null, null, 'Galinha branca isolada sobre tábua de madeira, em contexto de criação de fundo de quintal. Não representa granja industrial nem identifica a linhagem.'),
  ('hy-line-brown', null, 'Hy-Line Brown / W-36 — sem foto verificada', null, null, null, null, null, 'reprovada', false, null, null, 'Ave jovem dentro de caixa de papelão. Qualidade editorial inaceitável e não identifica a linhagem.'),
  ('concentrado-proteico', null, 'Concentrado proteico — sem foto verificada', null, null, null, null, null, 'reprovada', false, null, null, 'GRAVE: mostra ração PELETIZADA (processo que a Branorte não realiza) e é foto de marketing da RICHI Machinery, fabricante de peletizadoras — concorrente de equipamento.'),
  ('torta-dende', null, 'Torta de dendê — sem foto verificada', null, null, null, null, null, 'reprovada', false, null, null, 'Mostra frutos frescos de dendê, não a torta (coproduto) que entra na ração.'),
  ('brangus', null, 'Brangus — sem foto verificada', null, null, null, null, null, 'reprovada', false, null, null, 'Slide antigo escaneado, amarelado e de baixa resolução. O animal não evidencia a fração zebuína (sem cupim), ficando indistinguível de Angus puro.')
on conflict (slug) do update set arquivo_url = excluded.arquivo_url, alt = excluded.alt, legenda = excluded.legenda, autor = excluded.autor, licenca = excluded.licenca, fonte_url = excluded.fonte_url, url_original = excluded.url_original, status = excluded.status, identifica_item = excluded.identifica_item, verificada_em = excluded.verificada_em, aprovada_por = excluded.aprovada_por, motivo_reprovacao = excluded.motivo_reprovacao;
